@StackOverflowClone_HostAddress = http://localhost:5149

GET {{StackOverflowClone_HostAddress}}/api/tags
Accept: application/json

GET {{StackOverflowClone_HostAddress}}/api/users
Content-Type: application/json
{
  "username": "KowalJan"
  "email": "jan.kowalski@example.com",
  "password": "Haslo1234"
}

###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJTdGFja092ZXJmbG93Q2xvbmUiLCJpc3MiOiJTdGFja092ZXJmbG93Q2xvbmUiLCJleHAiOjE3OTA3OTAwNTEsImlhdCI6MTc5MDc4NjQ1MSwibmJmIjoxNzkwNzg2NDUxLCJzdWIiOiJjZWI2YTYxMy0wNDY5LTQ1YjYtZjdmMi0wOGRmMWYxMGMzMzkiLCJuYW1lIjoiVG9EZWxldGUifQ.cb1xsIPHhcqaqtykUa2gl_9K3vHqcXecijva3mK8GZc

GET {{StackOverflowClone_HostAddress}}/api/users/me
Authorization: Bearer {{token}}

###

POST {{StackOverflowClone_HostAddress}}/api/users/me/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "password": "Haslo1234"
}