// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StackOverflowClone.Api.Data;
using StackOverflowClone.Domain.Entities;

#nullable disable

namespace StackOverflowClone.Api.Migrations
{
    [DbContext(typeof(StackOverflowContext))]
    [Migration("20260925183058_CleanUpColumnConfiguration")]
    partial class CleanUpColumnConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(30000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.AnswerVote", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("UserId", "AnswerId");

                    b.HasIndex("AnswerId");

                    b.ToTable("AnswerVotes");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", t =>
                        {
                            t.HasCheckConstraint("CK_Comments_ExactlyOneParent", "([QuestionId] IS NOT NULL AND [AnswerId] IS NULL) OR ([QuestionId] IS NULL AND [AnswerId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.CommentVote", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentVotes");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(30000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.QuestionTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionTags", (string)null);
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.QuestionVote", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionVotes");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TagName = "javascript"
                        },
                        new
                        {
                            Id = 2,
                            TagName = "python"
                        },
                        new
                        {
                            Id = 3,
                            TagName = "java"
                        },
                        new
                        {
                            Id = 4,
                            TagName = "c#"
                        },
                        new
                        {
                            Id = 5,
                            TagName = "php"
                        },
                        new
                        {
                            Id = 6,
                            TagName = "android"
                        },
                        new
                        {
                            Id = 7,
                            TagName = "html"
                        },
                        new
                        {
                            Id = 8,
                            TagName = "jquery"
                        },
                        new
                        {
                            Id = 9,
                            TagName = "c++"
                        },
                        new
                        {
                            Id = 10,
                            TagName = "css"
                        },
                        new
                        {
                            Id = 11,
                            TagName = "ios"
                        },
                        new
                        {
                            Id = 12,
                            TagName = "sql"
                        },
                        new
                        {
                            Id = 13,
                            TagName = "mysql"
                        },
                        new
                        {
                            Id = 14,
                            TagName = "r"
                        },
                        new
                        {
                            Id = 15,
                            TagName = "reactjs"
                        },
                        new
                        {
                            Id = 16,
                            TagName = "node.js"
                        },
                        new
                        {
                            Id = 17,
                            TagName = "arrays"
                        },
                        new
                        {
                            Id = 18,
                            TagName = "c"
                        },
                        new
                        {
                            Id = 19,
                            TagName = "asp.net"
                        },
                        new
                        {
                            Id = 20,
                            TagName = "json"
                        },
                        new
                        {
                            Id = 21,
                            TagName = "python-3.x"
                        },
                        new
                        {
                            Id = 22,
                            TagName = ".net"
                        },
                        new
                        {
                            Id = 23,
                            TagName = "ruby-on-rails"
                        },
                        new
                        {
                            Id = 24,
                            TagName = "sql-server"
                        },
                        new
                        {
                            Id = 25,
                            TagName = "swift"
                        },
                        new
                        {
                            Id = 26,
                            TagName = "django"
                        },
                        new
                        {
                            Id = 27,
                            TagName = "angular"
                        },
                        new
                        {
                            Id = 28,
                            TagName = "objective-c"
                        },
                        new
                        {
                            Id = 29,
                            TagName = "excel"
                        },
                        new
                        {
                            Id = 30,
                            TagName = "pandas"
                        },
                        new
                        {
                            Id = 31,
                            TagName = "angularjs"
                        },
                        new
                        {
                            Id = 32,
                            TagName = "regex"
                        },
                        new
                        {
                            Id = 33,
                            TagName = "typescript"
                        },
                        new
                        {
                            Id = 34,
                            TagName = "ruby"
                        },
                        new
                        {
                            Id = 35,
                            TagName = "linux"
                        },
                        new
                        {
                            Id = 36,
                            TagName = "ajax"
                        },
                        new
                        {
                            Id = 37,
                            TagName = "iphone"
                        },
                        new
                        {
                            Id = 38,
                            TagName = "vba"
                        },
                        new
                        {
                            Id = 39,
                            TagName = "xml"
                        },
                        new
                        {
                            Id = 40,
                            TagName = "laravel"
                        },
                        new
                        {
                            Id = 41,
                            TagName = "spring"
                        },
                        new
                        {
                            Id = 42,
                            TagName = "asp.net-mvc"
                        },
                        new
                        {
                            Id = 43,
                            TagName = "database"
                        },
                        new
                        {
                            Id = 44,
                            TagName = "wordpress"
                        },
                        new
                        {
                            Id = 45,
                            TagName = "string"
                        },
                        new
                        {
                            Id = 46,
                            TagName = "postgresql"
                        },
                        new
                        {
                            Id = 47,
                            TagName = "docker"
                        },
                        new
                        {
                            Id = 48,
                            TagName = "git"
                        },
                        new
                        {
                            Id = 49,
                            TagName = "asp.net-core"
                        },
                        new
                        {
                            Id = 50,
                            TagName = "entity-framework-core"
                        },
                        new
                        {
                            Id = 51,
                            TagName = "linq"
                        },
                        new
                        {
                            Id = 52,
                            TagName = "unit-testing"
                        });
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.Answer", b =>
                {
                    b.HasOne("StackOverflowClone.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StackOverflowClone.Domain.Entities.User", "User")
                        .WithMany("Answers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.AnswerVote", b =>
                {
                    b.HasOne("StackOverflowClone.Domain.Entities.Answer", "Answer")
                        .WithMany("AnswerVotes")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StackOverflowClone.Domain.Entities.User", "User")
                        .WithMany("AnswerVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.Comment", b =>
                {
                    b.HasOne("StackOverflowClone.Domain.Entities.Answer", "Answer")
                        .WithMany("Comments")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StackOverflowClone.Domain.Entities.Question", "Question")
                        .WithMany("Comments")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StackOverflowClone.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.CommentVote", b =>
                {
                    b.HasOne("StackOverflowClone.Domain.Entities.Comment", "Comment")
                        .WithMany("CommentVotes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StackOverflowClone.Domain.Entities.User", "User")
                        .WithMany("CommentVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.Question", b =>
                {
                    b.HasOne("StackOverflowClone.Domain.Entities.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.QuestionTag", b =>
                {
                    b.HasOne("StackOverflowClone.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackOverflowClone.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.QuestionVote", b =>
                {
                    b.HasOne("StackOverflowClone.Domain.Entities.Question", "Question")
                        .WithMany("QuestionVotes")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StackOverflowClone.Domain.Entities.User", "User")
                        .WithMany("QuestionVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.Answer", b =>
                {
                    b.Navigation("AnswerVotes");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.Comment", b =>
                {
                    b.Navigation("CommentVotes");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Comments");

                    b.Navigation("QuestionVotes");
                });

            modelBuilder.Entity("StackOverflowClone.Domain.Entities.User", b =>
                {
                    b.Navigation("AnswerVotes");

                    b.Navigation("Answers");

                    b.Navigation("CommentVotes");

                    b.Navigation("Comments");

                    b.Navigation("QuestionVotes");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
